# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_processer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 821)
        MainWindow.setMaximumSize(QtCore.QSize(1067, 821))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 13, 1021, 701))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(791, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.noise_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.noise_comboBox.setMaximumSize(QtCore.QSize(491, 31))
        self.noise_comboBox.setObjectName("noise_comboBox")
        self.noise_comboBox.addItem("")
        self.noise_comboBox.addItem("")
        self.noise_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.noise_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(791, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.filters_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.filters_comboBox.setMaximumSize(QtCore.QSize(491, 31))
        self.filters_comboBox.setObjectName("filters_comboBox")
        self.filters_comboBox.addItem("")
        self.filters_comboBox.addItem("")
        self.filters_comboBox.addItem("")
        self.filters_comboBox.addItem("")
        self.filters_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.filters_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.Edge_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.Edge_comboBox.setMaximumSize(QtCore.QSize(491, 31))
        self.Edge_comboBox.setObjectName("Edge_comboBox")
        self.Edge_comboBox.addItem("")
        self.Edge_comboBox.addItem("")
        self.Edge_comboBox.addItem("")
        self.Edge_comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.Edge_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(331, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.original_image = QtWidgets.QLabel(self.layoutWidget)
        self.original_image.setMaximumSize(QtCore.QSize(331, 429))
        self.original_image.setText("")
        self.original_image.setScaledContents(True)
        self.original_image.setObjectName("original_image")
        self.verticalLayout.addWidget(self.original_image)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(241, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.noisy_image = QtWidgets.QLabel(self.layoutWidget)
        self.noisy_image.setMaximumSize(QtCore.QSize(331, 429))
        self.noisy_image.setText("")
        self.noisy_image.setScaledContents(True)
        self.noisy_image.setObjectName("noisy_image")
        self.verticalLayout_2.addWidget(self.noisy_image)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(281, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.filtered_image = QtWidgets.QLabel(self.layoutWidget)
        self.filtered_image.setMaximumSize(QtCore.QSize(331, 429))
        self.filtered_image.setText("")
        self.filtered_image.setScaledContents(True)
        self.filtered_image.setObjectName("filtered_image")
        self.verticalLayout_3.addWidget(self.filtered_image)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.setStretch(3, 5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(12, 12, 1021, 701))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.ip_img = QtWidgets.QLabel(self.layoutWidget1)
        self.ip_img.setMaximumSize(QtCore.QSize(501, 301))
        self.ip_img.setText("")
        self.ip_img.setScaledContents(True)
        self.ip_img.setObjectName("ip_img")
        self.verticalLayout_6.addWidget(self.ip_img)
        self.verticalLayout_6.setStretch(1, 5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.ip_img_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.ip_img_2.setMaximumSize(QtCore.QSize(501, 301))
        self.ip_img_2.setText("")
        self.ip_img_2.setScaledContents(True)
        self.ip_img_2.setObjectName("ip_img_2")
        self.verticalLayout_7.addWidget(self.ip_img_2)
        self.verticalLayout_7.setStretch(1, 5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.ip_img_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.ip_img_3.setMaximumSize(QtCore.QSize(501, 301))
        self.ip_img_3.setText("")
        self.ip_img_3.setScaledContents(True)
        self.ip_img_3.setObjectName("ip_img_3")
        self.verticalLayout_8.addWidget(self.ip_img_3)
        self.verticalLayout_8.setStretch(1, 5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.ip_img_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.ip_img_4.setMaximumSize(QtCore.QSize(501, 301))
        self.ip_img_4.setText("")
        self.ip_img_4.setScaledContents(True)
        self.ip_img_4.setObjectName("ip_img_4")
        self.verticalLayout_9.addWidget(self.ip_img_4)
        self.verticalLayout_9.setStretch(1, 5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_19.addWidget(self.label_10)
        self.ip_hyp_img1 = QtWidgets.QLabel(self.tab_3)
        self.ip_hyp_img1.setMaximumSize(QtCore.QSize(501, 301))
        self.ip_hyp_img1.setText("")
        self.ip_hyp_img1.setScaledContents(True)
        self.ip_hyp_img1.setObjectName("ip_hyp_img1")
        self.verticalLayout_19.addWidget(self.ip_hyp_img1)
        self.verticalLayout_19.setStretch(1, 5)
        self.horizontalLayout_11.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_20.addWidget(self.label_11)
        self.ip_hyp_img2 = QtWidgets.QLabel(self.tab_3)
        self.ip_hyp_img2.setMaximumSize(QtCore.QSize(501, 301))
        self.ip_hyp_img2.setText("")
        self.ip_hyp_img2.setScaledContents(True)
        self.ip_hyp_img2.setObjectName("ip_hyp_img2")
        self.verticalLayout_20.addWidget(self.ip_hyp_img2)
        self.verticalLayout_20.setStretch(1, 5)
        self.horizontalLayout_11.addLayout(self.verticalLayout_20)
        self.verticalLayout_22.addLayout(self.horizontalLayout_11)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_21.addWidget(self.label_23)
        self.op_hyp_img = QtWidgets.QLabel(self.tab_3)
        self.op_hyp_img.setMaximumSize(QtCore.QSize(1013, 303))
        self.op_hyp_img.setText("")
        self.op_hyp_img.setScaledContents(True)
        self.op_hyp_img.setObjectName("op_hyp_img")
        self.verticalLayout_21.addWidget(self.op_hyp_img)
        self.verticalLayout_21.setStretch(1, 5)
        self.verticalLayout_22.addLayout(self.verticalLayout_21)
        self.verticalLayout_22.setStretch(0, 2)
        self.verticalLayout_22.setStretch(1, 2)
        self.verticalLayout_23.addLayout(self.verticalLayout_22)
        self.tabWidget.addTab(self.tab_3, "")
        self.Image = QtWidgets.QWidget()
        self.Image.setObjectName("Image")
        self.layoutWidget2 = QtWidgets.QWidget(self.Image)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 11, 1021, 701))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.ip_img_eq = QtWidgets.QLabel(self.layoutWidget2)
        self.ip_img_eq.setMaximumSize(QtCore.QSize(501, 600))
        self.ip_img_eq.setText("")
        self.ip_img_eq.setScaledContents(True)
        self.ip_img_eq.setObjectName("ip_img_eq")
        self.verticalLayout_10.addWidget(self.ip_img_eq)
        self.verticalLayout_10.setStretch(1, 7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_11.addWidget(self.label_14)
        self.op_img_eq = QtWidgets.QLabel(self.layoutWidget2)
        self.op_img_eq.setMaximumSize(QtCore.QSize(501, 600))
        self.op_img_eq.setText("")
        self.op_img_eq.setScaledContents(True)
        self.op_img_eq.setObjectName("op_img_eq")
        self.verticalLayout_11.addWidget(self.op_img_eq)
        self.verticalLayout_11.setStretch(1, 7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.Image, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionHyprid_Image = QtWidgets.QAction(MainWindow)
        self.actionHyprid_Image.setObjectName("actionHyprid_Image")
        self.actionRGB_Histogram = QtWidgets.QAction(MainWindow)
        self.actionRGB_Histogram.setObjectName("actionRGB_Histogram")
        self.actionImage_Equalization = QtWidgets.QAction(MainWindow)
        self.actionImage_Equalization.setObjectName("actionImage_Equalization")
        self.actionImage_Normalization = QtWidgets.QAction(MainWindow)
        self.actionImage_Normalization.setObjectName("actionImage_Normalization")
        self.actionGlobal_Threshold = QtWidgets.QAction(MainWindow)
        self.actionGlobal_Threshold.setObjectName("actionGlobal_Threshold")
        self.actionLocal_Threshold = QtWidgets.QAction(MainWindow)
        self.actionLocal_Threshold.setObjectName("actionLocal_Threshold")
        self.actionActive_Contour = QtWidgets.QAction(MainWindow)
        self.actionActive_Contour.setObjectName("actionActive_Contour")
        self.actionCircle_Detection = QtWidgets.QAction(MainWindow)
        self.actionCircle_Detection.setObjectName("actionCircle_Detection")
        self.actionLine_Detection = QtWidgets.QAction(MainWindow)
        self.actionLine_Detection.setObjectName("actionLine_Detection")
        self.menuFile.addAction(self.actionLoad_Image)
        self.menuOptions.addAction(self.actionHistogram)
        self.menuOptions.addAction(self.actionHyprid_Image)
        self.menuOptions.addAction(self.actionRGB_Histogram)
        self.menuOptions.addAction(self.actionImage_Equalization)
        self.menuOptions.addAction(self.actionImage_Normalization)
        self.menuOptions.addAction(self.actionGlobal_Threshold)
        self.menuOptions.addAction(self.actionLocal_Threshold)
        self.menuOptions.addAction(self.actionActive_Contour)
        self.menuOptions.addAction(self.actionCircle_Detection)
        self.menuOptions.addAction(self.actionLine_Detection)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Processer"))
        self.label_3.setText(_translate("MainWindow", "Choose a certain type of noise"))
        self.noise_comboBox.setItemText(0, _translate("MainWindow", "Salt&pepper"))
        self.noise_comboBox.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.noise_comboBox.setItemText(2, _translate("MainWindow", "uniform"))
        self.label_5.setText(_translate("MainWindow", "Choose a certain type of filters"))
        self.filters_comboBox.setItemText(0, _translate("MainWindow", "average filter"))
        self.filters_comboBox.setItemText(1, _translate("MainWindow", "Gaussian filter"))
        self.filters_comboBox.setItemText(2, _translate("MainWindow", "Median filter"))
        self.filters_comboBox.setItemText(3, _translate("MainWindow", "Freq. low pass filter"))
        self.filters_comboBox.setItemText(4, _translate("MainWindow", "Freq. high pass filter"))
        self.label_12.setText(_translate("MainWindow", "Choose a certain type of Edge detector"))
        self.Edge_comboBox.setItemText(0, _translate("MainWindow", "Sobel Edge"))
        self.Edge_comboBox.setItemText(1, _translate("MainWindow", "Roberts Edge"))
        self.Edge_comboBox.setItemText(2, _translate("MainWindow", "Perwitt Edge"))
        self.Edge_comboBox.setItemText(3, _translate("MainWindow", "Canny Edge"))
        self.label.setText(_translate("MainWindow", "  Original Image"))
        self.label_2.setText(_translate("MainWindow", "  Noisy Image "))
        self.label_4.setText(_translate("MainWindow", "  filtered Image "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Filters"))
        self.label_7.setText(_translate("MainWindow", "            INPUT IMAGE"))
        self.label_8.setText(_translate("MainWindow", "               HISTOGRAM"))
        self.label_6.setText(_translate("MainWindow", "              HISTOGRAM"))
        self.label_9.setText(_translate("MainWindow", "             HISTOGRAM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Histogram"))
        self.label_10.setText(_translate("MainWindow", "            INPUT IMAGE(1)"))
        self.label_11.setText(_translate("MainWindow", "            INPUT IMAGE(2)"))
        self.label_23.setText(_translate("MainWindow", "                                     HYPRID IMAGE "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Hyprid "))
        self.label_13.setText(_translate("MainWindow", "            INPUT IMAGE"))
        self.label_14.setText(_translate("MainWindow", "           Equalized IMAGE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Image), _translate("MainWindow", "Image"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "more"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionHyprid_Image.setText(_translate("MainWindow", "Hyprid Image"))
        self.actionRGB_Histogram.setText(_translate("MainWindow", "RGB Histogram"))
        self.actionImage_Equalization.setText(_translate("MainWindow", "Image Equalization"))
        self.actionImage_Normalization.setText(_translate("MainWindow", "Image Normalization"))
        self.actionGlobal_Threshold.setText(_translate("MainWindow", "Global Threshold"))
        self.actionLocal_Threshold.setText(_translate("MainWindow", "Local Threshold"))
        self.actionActive_Contour.setText(_translate("MainWindow", "Active Contour"))
        self.actionCircle_Detection.setText(_translate("MainWindow", "Circle Detection"))
        self.actionLine_Detection.setText(_translate("MainWindow", "Line Detection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

